Fix for ident(1).

diff --git a/src/pgen/pgen.in b/src/pgen/pgen.in
--- a/src/pgen/pgen.in
+++ b/src/pgen/pgen.in
@@ -3,7 +3,7 @@
 # Produce a generated procmail.rc file.  Basically just a wrapper around
 # m4, but it makes life easier.
 #
-# @(#) $Id: pgen.in,v 1.2 2001/06/16 21:32:35 dom Exp $
+# @(#) $Id: pgen.in,v 1.3 2001/06/16 21:59:34 dom Exp $
 #
 
 me=`basename $0`
@@ -46,7 +46,7 @@ if [ $# != 1 ] ; then
 fi
 
 if [ ! -f "$1" ] ; then
-    echo "$me: file $1 not found" >&2
+    echo "${me}: file $1 not found" >&2
     exit 1
 fi
 m4 $MH "$M4DEFN" "$1"
